### ISSUE TITLE
gerar qr-code

### ISSUE THREAD

**Issue by hereisyumi** [Swag666baby/nexa#1]
como faço pra gerar qr-code no lugar de código de número de celular? 
porque não consigo conectar de jeito nenhum por código

**Comment by Swag666baby** [comment]
Qual exatamente é o problema com o código?

**Comment by hereisyumi** [comment]
o problema mesmo eh nao conseguir conectar pelo whatsapp usando número de celular, por qr-code seria possível.

**Comment by Swag666baby** [comment]
não o projetei pensando na conexão via qr-code, mas pelo pouco que testei, a própria biblioteca me entrega um erro não sendo capas de preencher os arquivos de autenticação. mas adoraria ajudar a solucionar a questão da conexão via número, ja que eu anteriormente ja testei e funcionou perfeitamente.

**Comment by Kurumi30** [comment]
> como faço pra gerar qr-code no lugar de código de número de celular? porque não consigo conectar de jeito nenhum por código

Rodei `node dist/index` e apareceu o qrcode
